version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v3er50ins8pz"
s3_prefix = "sam-hello-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

